"""Export: render an analysis memo as a self-contained HTML report,
optionally printed to PDF via headless Edge/Chrome.

The HTML is fully self-contained (inline CSS, no external requests) and opens
offline; PDF uses the local browser's --headless --print-to-pdf.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import markdown

from . import store
from .refresh import load_json

_EDGE_CANDIDATES = [
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
]

_CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font: 13px/1.75 "Segoe UI", "Microsoft YaHei", system-ui, sans-serif;
       color: #1c2330; max-width: 860px; margin: 0 auto; padding: 40px 32px; }
h1 { font-size: 21px; letter-spacing: 1px; border-bottom: 2px solid #b8860b;
     padding-bottom: 8px; }
h2 { font-size: 16px; color: #8a6510; margin-top: 28px; border-bottom: 1px solid #e3ddce;
     padding-bottom: 4px; }
h3 { font-size: 14px; color: #444; margin-top: 20px; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 12.5px; }
th, td { border: 1px solid #d8d2c4; padding: 6px 10px; text-align: left; vertical-align: top; }
th { background: #f4f0e6; }
code { background: #f1eee6; padding: 1px 5px; border-radius: 3px; font-size: 12px; }
blockquote { border-left: 3px solid #b8860b; margin: 10px 0; padding: 4px 14px;
             color: #555; background: #faf8f2; }
.verdict-card { border: 1px solid #d8d2c4; border-left: 4px solid #b8860b;
                background: #faf8f2; padding: 14px 18px; margin: 18px 0;
                display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px 20px; }
.verdict-card .k { color: #8a8471; font-size: 11px; }
.verdict-card .v { font-weight: 600; }
.meta-line { color: #8a8471; font-size: 11.5px; margin-bottom: 4px; }
.disclaimer { margin-top: 32px; padding-top: 10px; border-top: 1px solid #e3ddce;
              color: #999; font-size: 11px; }
@media print { body { padding: 0; } }
"""


def _fmt_targets(pt: dict | None) -> str:
    if not isinstance(pt, dict):
        return "—"
    horizon = pt.get("horizon", "12mo")
    return (f"bear {pt.get('bear', '—')} / base {pt.get('base', '—')} / "
            f"bull {pt.get('bull', '—')} ({horizon})")


def render_html(memo: dict, quote: dict | None) -> str:
    meta = memo["meta"]
    body_html = markdown.markdown(memo["body"], extensions=["tables", "fenced_code"])
    br = meta.get("buy_range")
    buy = f"{br[0]}–{br[1]}" if isinstance(br, list) and len(br) == 2 else "—"
    price = (quote or {}).get("price", meta.get("price_at_analysis", "—"))
    cells = [
        ("Verdict", f"{meta.get('action', '—')} (confidence: {meta.get('confidence', '—')})"),
        ("Price at analysis", f"{meta.get('price_at_analysis', '—')}"),
        ("Current price", f"{price}"),
        ("Good-buy range", buy),
        ("Price targets", _fmt_targets(meta.get("price_targets"))),
        ("Range verdict", str(meta.get("verdict", "—"))),
        ("Thesis health", str(meta.get("thesis_health", "—"))),
        ("Multiple basis", str(meta.get("multiple_basis", "—"))),
        ("Review trigger", str(meta.get("review_trigger", "—"))),
    ]
    card = "".join(f'<div><div class="k">{k}</div><div class="v">{v}</div></div>'
                   for k, v in cells)
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{meta.get('ticker', '')} · {meta.get('date', '')} · StockLux</title>
<style>{_CSS}</style></head><body>
<div class="meta-line">STOCKLUX · thesis: {meta.get('thesis', '—')} · layer:
{meta.get('layer', '—')} · {meta.get('date', '')}</div>
<div class="verdict-card">{card}</div>
{body_html}
<div class="disclaimer">Generated by StockLux · Analysis, not advice · Not
investment advice · Prices and P/E are a quotes.json snapshot from export time</div>
</body></html>"""


def export_memo(data_dir: Path, ticker: str, out_dir: Path,
                pdf: bool = False) -> dict:
    """Export the ticker's latest memo. Returns {"html", "pdf" | None, "pdf_error" | None}."""
    memo = store.latest_memo(data_dir, ticker)
    if memo is None:
        raise FileNotFoundError(f"no analysis memo found for {ticker}")
    quotes = load_json(Path(data_dir) / "quotes.json") or {"quotes": {}}
    html = render_html(memo, quotes["quotes"].get(ticker))
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{ticker}-{memo['meta'].get('date', 'memo')}"
    html_path = out_dir / f"{stem}.html"
    html_path.write_text(html, encoding="utf-8")
    result: dict = {"html": str(html_path), "pdf": None, "pdf_error": None}
    if pdf:
        pdf_path = out_dir / f"{stem}.pdf"
        browser = _find_browser()
        if browser is None:
            result["pdf_error"] = "Edge/Chrome not found — open the HTML and print (Ctrl+P)"
        else:
            try:
                subprocess.run(
                    [browser, "--headless=new", "--disable-gpu",
                     f"--print-to-pdf={pdf_path}", "--no-pdf-header-footer",
                     html_path.resolve().as_uri()],
                    check=True, capture_output=True, timeout=60)
                result["pdf"] = str(pdf_path)
            except (subprocess.SubprocessError, OSError) as e:
                result["pdf_error"] = f"headless print failed: {e}; open the HTML and print (Ctrl+P)"
    return result


def _find_browser() -> str | None:
    for name in ("msedge", "chrome"):
        found = shutil.which(name)
        if found:
            return found
    for candidate in _EDGE_CANDIDATES:
        if Path(candidate).exists():
            return candidate
    return None
